#culture="zh-CN"
ConvertFrom-StringData @'
    infoLoadLibrary = 正在加载库
    successLoadLibrary = 加载成功！
    errorLoadLibrary = 加载失败！
    infoDwlAllSongsID = 正在下载全部歌曲 ID
    infoLoadSongID = 正在读取文件内的歌曲 ID
    successLoadSongID1 = 已读取到
    successLoadSongID2 = 首歌曲 ID！
    errorLoadSongID = 未读取到任何歌曲 ID！请检查你的歌曲 ID 列表文件。
    infoDownloadBandInfo = 正在下载乐队信息
    successDownloadBandInfo = 乐队信息下载成功！
    errorDownloadBandInfo = 未下载到任何乐队信息！请检查你的网络设置。
    errorSpecifiedServerNotFound = 指定的服务器未找到。
    infoSongIDGetInfo1 = 正在根据歌曲
    infoSongIDGetInfo2 = 下载歌曲信息
    successSongIDGetInfo = 歌曲信息下载成功！
    errorSongIDGetInfo = 未下载到任何歌曲信息！请检查你的网络设置。
    infoBandTitle = 乐团 - 标题:
    infoLyCoAr = 作词、作曲、编曲：
    errorTagLibNotFound = 未找到库 TagLibSharp.dll！无法写入歌曲信息！
    errorParsedSongInfo = 获取歌曲信息失败！请检查你的歌曲 ID、指定的下载服务器和网络设置。
    infoClean = 已启用清理，正在删除 Jacket 和 Origin 文件夹。
    infoFolderNotFound1 = 文件夹
    infoFolderNotFound2 = 未找到，正在创建
    successFolderNotFound = 文件夹创建成功！
    errorFolderNotFound1 = 创建文件夹
    errorFolderNotFound2 = 错误！
    infoDownloadingTo1 = 正在下载
    infoDownloadingTo2 = 至
    successDownloadingTo = 资源下载成功！
    errorDownloadingTo = 下载出现错误！请检查你的歌曲 ID、指定的下载服务器和网络设置。
    errorDownloadJacketType = 下载出现错误！该图片不存在于此服务器。请检查你的歌曲 ID 和指定的下载服务器。
    infoDownloadFileExist = 已存在。跳过下载！
    infoCopyTo1 = 正在复制
    infoCopyTo2 = 至
    successCopyTo = 资源复制成功！
    errorCopyTo = 资源复制失败！
    infoWriteByTagLib = 正在使用 TagLibSharp.dll 写入歌曲信息
    successWriteByTagLib = 图片未找到，跳过！
    errorWriteByTagLibImgNotFound = 信息写入成功！
    errorWriteByTagLib = 信息写入失败！
'@