name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Enter the version number'
        required: true
        default: 'v.'

jobs:
  build-taglibsharp:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'mono/taglib-sharp'
        fetch-depth: '1'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.302

    - name: Clean
      run: dotnet clean --configuration Release && dotnet nuget locals all --clear

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Run unit tests
      run: dotnet test --verbosity normal

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: taglibsharp.dll
        path: src/TaglibSharp/bin/Release/netstandard2.0/TagLibSharp.dll

  pack:
    runs-on: ubuntu-latest
    needs: build-taglibsharp
    steps:
      - uses: actions/checkout@v3

      - name: Install environment
        run: sudo apt install -y zip

      - uses: actions/download-artifact@v3
        with:
          name: taglibsharp.dll

      - name: Pack script to zip
        run: |
          zip -r -l -9 Bestdori-Music-Downloader-CRLF-UTF-8-${{ github.event.inputs.releaseVersion }}.zip bmd.ps1 README.md Localized
          zip -r -9 Bestdori-Music-Downloader-CRLF-UTF-8-${{ github.event.inputs.releaseVersion }}.zip TagLibSharp.dll
          zip -r -9 Bestdori-Music-Downloader-LF-UTF-8-${{ github.event.inputs.releaseVersion }}.zip bmd.ps1 README.md Localized
          zip -r -9 Bestdori-Music-Downloader-LF-UTF-8-${{ github.event.inputs.releaseVersion }}.zip TagLibSharp.dll

      - name: Upload zip file
        uses: actions/upload-artifact@v3
        with:
          name: Bestdori-Music-Downloader-CRLF-UTF-8-Build${{ github.event.inputs.releaseVersion }}
          path: Bestdori-Music-Downloader-CRLF-UTF-8-${{ github.event.inputs.releaseVersion }}.zip

  upload-release:
    permissions:
      contents: write
    needs:
      - pack
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Bestdori-Music-Downloader-CRLF-UTF-8-Build${{ github.event.inputs.releaseVersion }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Bestdori Music Downloader ${{ github.event.inputs.releaseVersion }}
          tag_name: ${{ github.event.inputs.releaseVersion }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            Bestdori-Music-Downloader*.zip